FROM php:7-apache

ARG APACHE_DOCUMENT_ROOT

RUN apt-get update && apt-get install -y \
        libfreetype6-dev libjpeg62-turbo-dev \
        libpng-dev libpq-dev libxml2-dev \
	libcurl4-openssl-dev libxslt-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install -j$(nproc) bcmath \
    && docker-php-ext-install -j$(nproc) curl \
    && docker-php-ext-install -j$(nproc) mbstring \
    && docker-php-ext-install -j$(nproc) xsl \
    && docker-php-ext-install -j$(nproc) pdo \
    && docker-php-ext-install -j$(nproc) pdo_pgsql

COPY CDash/ /var/www/html/CDash/
COPY config.local.php /var/www/html/CDash/config/

RUN sed -ri -e "s!/var/www/html!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/sites-available/*.conf \
    && sed -ri -e "s!/var/www/!${APACHE_DOCUMENT_ROOT}!g" /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf \
    && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT}/../backup \
    && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT}/../log \
    && mkdir -p ${APACHE_DOCUMENT_ROOT}/upload && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT}/upload \
    && mkdir -p ${APACHE_DOCUMENT_ROOT}/rss && chown -R www-data:www-data ${APACHE_DOCUMENT_ROOT}/rss
